In [2]:
# Import packages
import numpy as np
import pandas as pd
import pandas_datareader as pddr
import datetime as dt
import os
from bokeh.io import output_file
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, Title, Legend, HoverTool
from usempl_streaks import get_usempl_data, usempl_streaks

In [3]:
fig, end_date_str = usempl_streaks()

End date of U.S. employment series is 2024-01-01
PAYEMS data downloaded on 2024-02-06:
    has start PAYEMS data month of 1919-07,
    and end PAYEMS data month of 2024-01-01.
                  Date        PAYEMS empl_mth_gain strk_mths     strk_cum  \
0  1919-08-01 00:00:00  27475.457629    397.457629         1   397.457629
1  1919-09-01 00:00:00  27784.678727    309.221098         2   706.678727
2  1919-10-01 00:00:00  28011.645656    226.966928         3   933.645656
3  1919-11-01 00:00:00  28162.340775     150.69512         4  1084.340775
4  1919-12-01 00:00:00  28242.746448     80.405673         5  1164.746448
5  1920-01-01 00:00:00  28258.845035     16.098587         6  1180.845035

   strk_mths_tot  strk_avg_emp_gain  strk_cum_tot
0              6         196.807506   1180.845035
1              6         196.807506   1180.845035
2              6         196.807506   1180.845035
3              6         196.807506   1180.845035
4              6         196.807506   1180.845035
5              6         196.807506   1180.845035
                   Date        PAYEMS empl_mth_gain strk_mths     strk_cum  \
0   1921-10-01 00:00:00  24294.623182     17.937034         1    17.937034
1   1921-11-01 00:00:00  24351.786742     57.163561         2    75.100595
2   1921-12-01 00:00:00  24444.799745     93.013003         3   168.113597
3   1922-01-01 00:00:00  24570.285105     125.48536         4   293.598957
4   1922-02-01 00:00:00  24724.865736    154.580632         5   448.179588
5   1922-03-01 00:00:00  24905.164555    180.298819         6   628.478407
6   1922-04-01 00:00:00  25107.804475    202.639921         7   831.118328
7   1922-05-01 00:00:00  25329.408413    221.603938         8  1052.722265
8   1922-06-01 00:00:00  25566.599283     237.19087         9  1289.913135
9   1922-07-01 00:00:00       25816.0    249.400717        10  1539.313852
10  1922-08-01 00:00:00  26074.146721    258.146721        11  1797.460574
11  1922-09-01 00:00:00  26337.228572    263.081851        12  2060.542425
12  1922-10-01 00:00:00   26601.34792    264.119348        13  2324.661772
13  1922-11-01 00:00:00  26862.607132    261.259212        14  2585.920984
14  1922-12-01 00:00:00  27117.108575    254.501443        15  2840.422427
15  1923-01-01 00:00:00  27360.954616    243.846042        16  3084.268469
16  1923-02-01 00:00:00  27590.247624    229.293007        17  3313.561476
17  1923-03-01 00:00:00  27801.089964     210.84234        18  3524.403816
18  1923-04-01 00:00:00  27989.584004    188.494041        19  3712.897857
19  1923-05-01 00:00:00  28151.832112    162.248108        20  3875.145965
20  1923-06-01 00:00:00  28283.936655    132.104543        21  4007.250508
21  1923-07-01 00:00:00       28382.0     98.063345        22  4105.313852
22  1923-08-01 00:00:00  28443.596268     61.596268        23  4166.910121
23  1923-09-01 00:00:00    28472.1866     28.590331        24  4195.500452
24  1923-10-01 00:00:00  28472.703888      0.517288        25   4196.01774

    strk_mths_tot  strk_avg_emp_gain  strk_cum_tot
0              25          167.84071    4196.01774
1              25          167.84071    4196.01774
2              25          167.84071    4196.01774
3              25          167.84071    4196.01774
4              25          167.84071    4196.01774
5              25          167.84071    4196.01774
6              25          167.84071    4196.01774
7              25          167.84071    4196.01774
8              25          167.84071    4196.01774
9              25          167.84071    4196.01774
10             25          167.84071    4196.01774
11             25          167.84071    4196.01774
12             25          167.84071    4196.01774
13             25          167.84071    4196.01774
14             25          167.84071    4196.01774
15             25          167.84071    4196.01774
16             25          167.84071    4196.01774
17             25          167.84071    4196.01774
18             25          167.84071    4196.01774
19             25          167.84071    4196.01774
20             25          167.84071    4196.01774
21             25          167.84071    4196.01774
22             25          167.84071    4196.01774
23             25          167.84071    4196.01774
24             25          167.84071    4196.01774
                   Date        PAYEMS empl_mth_gain strk_mths     strk_cum  \
0   1924-09-01 00:00:00  28027.358361      9.390157         1     9.390157
1   1924-10-01 00:00:00  28054.336528     26.978166         2    36.368323
2   1924-11-01 00:00:00  28097.068762     42.732234         3    79.100557
3   1924-12-01 00:00:00  28153.721121     56.652359         4   135.752916
4   1925-01-01 00:00:00  28222.459663     68.738542         5   204.491458
5   1925-02-01 00:00:00  28301.450447     78.990783         6   283.482242
6   1925-03-01 00:00:00  28388.859529     87.409082         7   370.891324
7   1925-04-01 00:00:00  28482.852967     93.993439         8   464.884762
8   1925-05-01 00:00:00   28581.59682     98.743853         9   563.628615
9   1925-06-01 00:00:00  28683.257145    101.660325        10    665.28894
10  1925-07-01 00:00:00       28786.0    102.742855        11   768.031795
11  1925-08-01 00:00:00  28888.205681    102.205681        12   870.237476
12  1925-09-01 00:00:00  28989.111436    100.905755        13   971.143231
13  1925-10-01 00:00:00   29088.16875     99.057315        14  1070.200546
14  1925-11-01 00:00:00  29184.829112     96.660361        15  1166.860907
15  1925-12-01 00:00:00  29278.544005     93.714893        16    1260.5758
16  1926-01-01 00:00:00  29368.764917     90.220912        17  1350.796712
17  1926-02-01 00:00:00  29454.943333     86.178416        18  1436.975129
18  1926-03-01 00:00:00  29536.530741     81.587407        19  1518.562536
19  1926-04-01 00:00:00  29612.978625     76.447884        20   1595.01042
20  1926-05-01 00:00:00  29683.738472     70.759847        21  1665.770267
21  1926-06-01 00:00:00  29748.261768     64.523296        22  1730.293563
22  1926-07-01 00:00:00       29806.0     57.738232        23  1788.031795
23  1926-08-01 00:00:00  29856.515785     50.515785        24   1838.54758
24  1926-09-01 00:00:00  29899.816266     43.300482        25  1881.848061
25  1926-10-01 00:00:00   29936.01972     36.203454        26  1918.051515
26  1926-11-01 00:00:00  29965.244422     29.224702        27  1947.276217
27  1926-12-01 00:00:00  29987.608646     22.364225        28  1969.640442
28  1927-01-01 00:00:00  30003.230669     15.622023        29  1985.262465
29  1927-02-01 00:00:00  30012.228767      8.998097        30  1994.260562
30  1927-03-01 00:00:00  30014.721213      2.492446        31  1996.753008

    strk_mths_tot  strk_avg_emp_gain  strk_cum_tot
0              31          64.411387   1996.753008
1              31          64.411387   1996.753008
2              31          64.411387   1996.753008
3              31          64.411387   1996.753008
4              31          64.411387   1996.753008
5              31          64.411387   1996.753008
6              31          64.411387   1996.753008
7              31          64.411387   1996.753008
8              31          64.411387   1996.753008
9              31          64.411387   1996.753008
10             31          64.411387   1996.753008
11             31          64.411387   1996.753008
12             31          64.411387   1996.753008
13             31          64.411387   1996.753008
14             31          64.411387   1996.753008
15             31          64.411387   1996.753008
16             31          64.411387   1996.753008
17             31          64.411387   1996.753008
18             31          64.411387   1996.753008
19             31          64.411387   1996.753008
20             31          64.411387   1996.753008
21             31          64.411387   1996.753008
22             31          64.411387   1996.753008
23             31          64.411387   1996.753008
24             31          64.411387   1996.753008
25             31          64.411387   1996.753008
26             31          64.411387   1996.753008
27             31          64.411387   1996.753008
28             31          64.411387   1996.753008
29             31          64.411387   1996.753008
30             31          64.411387   1996.753008
                   Date        PAYEMS empl_mth_gain strk_mths     strk_cum  \
0   1928-03-01 00:00:00  29793.473296      4.033085         1     4.033085
1   1928-04-01 00:00:00  29812.528739     19.055442         2    23.088527
2   1928-05-01 00:00:00  29849.223618     36.694879         3    59.783406
3   1928-06-01 00:00:00  29906.175012     56.951394         4     116.7348
4   1928-07-01 00:00:00       29986.0     79.824988         5   196.559788
5   1928-08-01 00:00:00  30089.951855    103.951855         6   300.511644
6   1928-09-01 00:00:00  30213.828626    123.876771         7   424.388414
7   1928-10-01 00:00:00  30352.064554    138.235928         8   562.624343
8   1928-11-01 00:00:00  30499.093883    147.029329         9   709.653671
9   1928-12-01 00:00:00  30649.350854    150.256971        10   859.910642
10  1929-01-01 00:00:00   30797.26971    147.918856        11  1007.829498
11  1929-02-01 00:00:00  30937.284693    140.014983        12  1147.844481
12  1929-03-01 00:00:00  31063.830046    126.545353        13  1274.389834
13  1929-04-01 00:00:00   31171.34001    107.509965        14  1381.899799
14  1929-05-01 00:00:00  31254.248829     82.908819        15  1464.808618
15  1929-06-01 00:00:00  31306.990745     52.741916        16  1517.550534
16  1929-07-01 00:00:00       31324.0     17.009255        17  1534.559788

    strk_mths_tot  strk_avg_emp_gain  strk_cum_tot
0              17          90.268223   1534.559788
1              17          90.268223   1534.559788
2              17          90.268223   1534.559788
3              17          90.268223   1534.559788
4              17          90.268223   1534.559788
5              17          90.268223   1534.559788
6              17          90.268223   1534.559788
7              17          90.268223   1534.559788
8              17          90.268223   1534.559788
9              17          90.268223   1534.559788
10             17          90.268223   1534.559788
11             17          90.268223   1534.559788
12             17          90.268223   1534.559788
13             17          90.268223   1534.559788
14             17          90.268223   1534.559788
15             17          90.268223   1534.559788
16             17          90.268223   1534.559788
                   Date        PAYEMS empl_mth_gain strk_mths     strk_cum  \
0   1933-02-01 00:00:00   23231.10403     24.490023         1    24.490023
1   1933-03-01 00:00:00  23279.761903     48.657872         2    73.147895
2   1933-04-01 00:00:00   23351.73403     71.972128         3   145.120023
3   1933-05-01 00:00:00  23446.166819     94.432788         4   239.552811
4   1933-06-01 00:00:00  23562.206673    116.039855         5   355.592666
5   1933-07-01 00:00:00       23699.0    136.793327         6   492.385993
6   1933-08-01 00:00:00  23855.283145    156.283145         7   648.669138
7   1933-09-01 00:00:00  24028.152218    172.869073         8    821.53821
8   1933-10-01 00:00:00  24214.293268    186.141051         9  1007.679261
9   1933-11-01 00:00:00  24410.392347    196.099079        10  1203.778339
10  1933-12-01 00:00:00  24613.135503    202.743157        11  1406.521496
11  1934-01-01 00:00:00  24819.208788    206.073285        12  1612.594781
12  1934-02-01 00:00:00  25025.298252    206.089463        13  1818.684244
13  1934-03-01 00:00:00  25228.089944    202.791692        14  2021.475936
14  1934-04-01 00:00:00  25424.269914    196.179971        15  2217.655907
15  1934-05-01 00:00:00  25610.524214      186.2543        16  2403.910206
16  1934-06-01 00:00:00  25783.538892    173.014679        17  2576.924885
17  1934-07-01 00:00:00       25940.0    156.461108        18  2733.385993
18  1934-08-01 00:00:00  26077.588334    137.588334        19  2870.974327
19  1934-09-01 00:00:00   26197.96368    120.375346        20  2991.349673
20  1934-10-01 00:00:00  26303.780571    105.816891        21  3097.166564
21  1934-11-01 00:00:00  26397.693539     93.912968        22  3191.079532
22  1934-12-01 00:00:00  26482.357118     84.663578        23   3275.74311
23  1935-01-01 00:00:00  26560.425839     78.068721        24  3353.811832
24  1935-02-01 00:00:00  26634.554236     74.128397        25  3427.940229
25  1935-03-01 00:00:00  26707.396841     72.842605        26  3500.782834
26  1935-04-01 00:00:00  26781.608188     74.211346        27   3574.99418
27  1935-05-01 00:00:00  26859.842808      78.23462        28    3653.2288
28  1935-06-01 00:00:00  26944.755234     84.912427        29  3738.141227
29  1935-07-01 00:00:00       27039.0     94.244766        30  3832.385993
30  1935-08-01 00:00:00  27144.770926    105.770926        31  3938.156919
31  1935-09-01 00:00:00  27262.418987    117.648061        32   4055.80498
32  1935-10-01 00:00:00  27391.834448     129.41546        33   4185.22044
33  1935-11-01 00:00:00   27532.90757    141.073122        34  4326.293562
34  1935-12-01 00:00:00  27685.528618    152.621048        35   4478.91461
35  1936-01-01 00:00:00  27849.587855    164.059237        36  4642.973847
36  1936-02-01 00:00:00  28024.975544     175.38769        37  4818.361537
37  1936-03-01 00:00:00   28211.58195    186.606405        38  5004.967942
38  1936-04-01 00:00:00  28409.297335    197.715385        39  5202.683327
39  1936-05-01 00:00:00  28618.011962    208.714628        40  5411.397955
40  1936-06-01 00:00:00  28837.616096    219.604134        41  5631.002089
41  1936-07-01 00:00:00       29068.0    230.383904        42  5861.385993
42  1936-08-01 00:00:00  29308.114999    240.114999        43  6101.500991
43  1936-09-01 00:00:00  29553.156667    245.041668        44  6346.542659
44  1936-10-01 00:00:00  29797.381639    244.224972        45  6590.767631
45  1936-11-01 00:00:00  30035.046552    237.664913        46  6828.432544
46  1936-12-01 00:00:00  30260.408041    225.361489        47  7053.794033
47  1937-01-01 00:00:00  30467.722741    207.314701        48  7261.108734
48  1937-02-01 00:00:00   30651.24729    183.524549        49  7444.633283
49  1937-03-01 00:00:00  30805.238322    153.991032        50  7598.624315
50  1937-04-01 00:00:00  30923.952473    118.714151        51  7717.338466
51  1937-05-01 00:00:00   31001.64638     77.693906        52  7795.032372
52  1937-06-01 00:00:00  31032.576677     30.930297        53  7825.962669

    strk_mths_tot  strk_avg_emp_gain  strk_cum_tot
0              53         147.659673   7825.962669
1              53         147.659673   7825.962669
2              53         147.659673   7825.962669
3              53         147.659673   7825.962669
4              53         147.659673   7825.962669
5              53         147.659673   7825.962669
6              53         147.659673   7825.962669
7              53         147.659673   7825.962669
8              53         147.659673   7825.962669
9              53         147.659673   7825.962669
10             53         147.659673   7825.962669
11             53         147.659673   7825.962669
12             53         147.659673   7825.962669
13             53         147.659673   7825.962669
14             53         147.659673   7825.962669
15             53         147.659673   7825.962669
16             53         147.659673   7825.962669
17             53         147.659673   7825.962669
18             53         147.659673   7825.962669
19             53         147.659673   7825.962669
20             53         147.659673   7825.962669
21             53         147.659673   7825.962669
22             53         147.659673   7825.962669
23             53         147.659673   7825.962669
24             53         147.659673   7825.962669
25             53         147.659673   7825.962669
26             53         147.659673   7825.962669
27             53         147.659673   7825.962669
28             53         147.659673   7825.962669
29             53         147.659673   7825.962669
30             53         147.659673   7825.962669
31             53         147.659673   7825.962669
32             53         147.659673   7825.962669
33             53         147.659673   7825.962669
34             53         147.659673   7825.962669
35             53         147.659673   7825.962669
36             53         147.659673   7825.962669
37             53         147.659673   7825.962669
38             53         147.659673   7825.962669
39             53         147.659673   7825.962669
40             53         147.659673   7825.962669
41             53         147.659673   7825.962669
42             53         147.659673   7825.962669
43             53         147.659673   7825.962669
44             53         147.659673   7825.962669
45             53         147.659673   7825.962669
46             53         147.659673   7825.962669
47             53         147.659673   7825.962669
48             53         147.659673   7825.962669
49             53         147.659673   7825.962669
50             53         147.659673   7825.962669
51             53         147.659673   7825.962669
52             53         147.659673   7825.962669
                  Date        PAYEMS empl_mth_gain strk_mths    strk_cum  \
0  1938-08-01 00:00:00   29219.62261      25.62261         1    25.62261
1  1938-09-01 00:00:00  29299.204001     79.581392         2  105.204001
2  1938-10-01 00:00:00  29421.038306    121.834304         3  227.038306
3  1938-11-01 00:00:00  29573.419653    152.381347         4  379.419653
4  1938-12-01 00:00:00  29744.642174    171.222521         5  550.642174
5  1939-01-01 00:00:00       29923.0    178.357826         6       729.0
6  1939-02-01 00:00:00       30100.0         177.0         7       906.0
7  1939-03-01 00:00:00       30280.0         180.0         8      1086.0

   strk_mths_tot  strk_avg_emp_gain  strk_cum_tot
0              8             135.75        1086.0
1              8             135.75        1086.0
2              8             135.75        1086.0
3              8             135.75        1086.0
4              8             135.75        1086.0
5              8             135.75        1086.0
6              8             135.75        1086.0
7              8             135.75        1086.0
                  Date   PAYEMS empl_mth_gain strk_mths strk_cum  \
0  1939-05-01 00:00:00  30299.0         205.0         1    205.0
1  1939-06-01 00:00:00  30502.0         203.0         2    408.0

   strk_mths_tot  strk_avg_emp_gain  strk_cum_tot
0              2              204.0         408.0
1              2              204.0         408.0
                  Date   PAYEMS empl_mth_gain strk_mths strk_cum  \
0  1939-08-01 00:00:00  30663.0         244.0         1    244.0
1  1939-09-01 00:00:00  31031.0         368.0         2    612.0
2  1939-10-01 00:00:00  31411.0         380.0         3    992.0
3  1939-11-01 00:00:00  31470.0          59.0         4   1051.0
4  1939-12-01 00:00:00  31542.0          72.0         5   1123.0
5  1940-01-01 00:00:00  31603.0          61.0         6   1184.0
6  1940-02-01 00:00:00  31715.0         112.0         7   1296.0
7  1940-03-01 00:00:00  31825.0         110.0         8   1406.0

   strk_mths_tot  strk_avg_emp_gain  strk_cum_tot
0              8             175.75        1406.0
1              8             175.75        1406.0
2              8             175.75        1406.0
3              8             175.75        1406.0
4              8             175.75        1406.0
5              8             175.75        1406.0
6              8             175.75        1406.0
7              8             175.75        1406.0

           Date  PAYEMS  empl_mth_gain
0    1939-01-01   29923            NaN
1    1939-02-01   30100          177.0
2    1939-03-01   30280          180.0
3    1939-04-01   30094         -186.0
4    1939-05-01   30299          205.0
...         ...     ...            ...
1016 2023-09-01  156667          246.0
1017 2023-10-01  156832          165.0
1018 2023-11-01  157014          182.0
1019 2023-12-01  157347          333.0
1020 2024-01-01  157700          353.0

[1021 rows x 3 columns]

In [4]:
from bokeh.palettes import Plasma256

In [5]:
len(Plasma256)

256

In [6]:
Plasma256

('#0C0786',
 '#100787',
 '#130689',
 '#15068A',
 '#18068B',
 '#1B068C',
 '#1D068D',
 '#1F058E',
 '#21058F',
 '#230590',
 '#250591',
 '#270592',
 '#290593',
 '#2B0594',
 '#2D0494',
 '#2F0495',
 '#310496',
 '#330497',
 '#340498',
 '#360498',
 '#380499',
 '#3A049A',
 '#3B039A',
 '#3D039B',
 '#3F039C',
 '#40039C',
 '#42039D',
 '#44039E',
 '#45039E',
 '#47029F',
 '#49029F',
 '#4A02A0',
 '#4C02A1',
 '#4E02A1',
 '#4F02A2',
 '#5101A2',
 '#5201A3',
 '#5401A3',
 '#5601A3',
 '#5701A4',
 '#5901A4',
 '#5A00A5',
 '#5C00A5',
 '#5E00A5',
 '#5F00A6',
 '#6100A6',
 '#6200A6',
 '#6400A7',
 '#6500A7',
 '#6700A7',
 '#6800A7',
 '#6A00A7',
 '#6C00A8',
 '#6D00A8',
 '#6F00A8',
 '#7000A8',
 '#7200A8',
 '#7300A8',
 '#7500A8',
 '#7601A8',
 '#7801A8',
 '#7901A8',
 '#7B02A8',
 '#7C02A7',
 '#7E03A7',
 '#7F03A7',
 '#8104A7',
 '#8204A7',
 '#8405A6',
 '#8506A6',
 '#8607A6',
 '#8807A5',
 '#8908A5',
 '#8B09A4',
 '#8C0AA4',
 '#8E0CA4',
 '#8F0DA3',
 '#900EA3',
 '#920FA2',
 '#9310A1',
 '#9511A1',
 '#9612A0',
 '#9713A0',
 '#99149F',
 '#9A159E',
 '#9B179E',
 '#9D189D',
 '#9E199C',
 '#9F1A9B',
 '#A01B9B',
 '#A21C9A',
 '#A31D99',
 '#A41E98',
 '#A51F97',
 '#A72197',
 '#A82296',
 '#A92395',
 '#AA2494',
 '#AC2593',
 '#AD2692',
 '#AE2791',
 '#AF2890',
 '#B02A8F',
 '#B12B8F',
 '#B22C8E',
 '#B42D8D',
 '#B52E8C',
 '#B62F8B',
 '#B7308A',
 '#B83289',
 '#B93388',
 '#BA3487',
 '#BB3586',
 '#BC3685',
 '#BD3784',
 '#BE3883',
 '#BF3982',
 '#C03B81',
 '#C13C80',
 '#C23D80',
 '#C33E7F',
 '#C43F7E',
 '#C5407D',
 '#C6417C',
 '#C7427B',
 '#C8447A',
 '#C94579',
 '#CA4678',
 '#CB4777',
 '#CC4876',
 '#CD4975',
 '#CE4A75',
 '#CF4B74',
 '#D04D73',
 '#D14E72',
 '#D14F71',
 '#D25070',
 '#D3516F',
 '#D4526E',
 '#D5536D',
 '#D6556D',
 '#D7566C',
 '#D7576B',
 '#D8586A',
 '#D95969',
 '#DA5A68',
 '#DB5B67',
 '#DC5D66',
 '#DC5E66',
 '#DD5F65',
 '#DE6064',
 '#DF6163',
 '#DF6262',
 '#E06461',
 '#E16560',
 '#E26660',
 '#E3675F',
 '#E3685E',
 '#E46A5D',
 '#E56B5C',
 '#E56C5B',
 '#E66D5A',
 '#E76E5A',
 '#E87059',
 '#E87158',
 '#E97257',
 '#EA7356',
 '#EA7455',
 '#EB7654',
 '#EC7754',
 '#EC7853',
 '#ED7952',
 '#ED7B51',
 '#EE7C50',
 '#EF7D4F',
 '#EF7E4E',
 '#F0804D',
 '#F0814D',
 '#F1824C',
 '#F2844B',
 '#F2854A',
 '#F38649',
 '#F38748',
 '#F48947',
 '#F48A47',
 '#F58B46',
 '#F58D45',
 '#F68E44',
 '#F68F43',
 '#F69142',
 '#F79241',
 '#F79341',
 '#F89540',
 '#F8963F',
 '#F8983E',
 '#F9993D',
 '#F99A3C',
 '#FA9C3B',
 '#FA9D3A',
 '#FA9F3A',
 '#FAA039',
 '#FBA238',
 '#FBA337',
 '#FBA436',
 '#FCA635',
 '#FCA735',
 '#FCA934',
 '#FCAA33',
 '#FCAC32',
 '#FCAD31',
 '#FDAF31',
 '#FDB030',
 '#FDB22F',
 '#FDB32E',
 '#FDB52D',
 '#FDB62D',
 '#FDB82C',
 '#FDB92B',
 '#FDBB2B',
 '#FDBC2A',
 '#FDBE29',
 '#FDC029',
 '#FDC128',
 '#FDC328',
 '#FDC427',
 '#FDC626',
 '#FCC726',
 '#FCC926',
 '#FCCB25',
 '#FCCC25',
 '#FCCE25',
 '#FBD024',
 '#FBD124',
 '#FBD324',
 '#FAD524',
 '#FAD624',
 '#FAD824',
 '#F9D924',
 '#F9DB24',
 '#F8DD24',
 '#F8DF24',
 '#F7E024',
 '#F7E225',
 '#F6E425',
 '#F6E525',
 '#F5E726',
 '#F5E926',
 '#F4EA26',
 '#F3EC26',
 '#F3EE26',
 '#F2F026',
 '#F2F126',
 '#F1F326',
 '#F0F525',
 '#F0F623',
 '#EFF821')

In [7]:
type(Plasma256)

tuple

In [8]:
Plasma256[0]

'#0C0786'